### ISSUE TITLE
Разные варианты схемы Q128

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/quorum-reborn#2]
Собственно, в наличии два варианта схемы Кворума-128: 
1. https://github.com/UncleRus/quorum-reborn/blob/master/resources/Quorum-128/Schematics/Q128P1M.PNG
    https://github.com/UncleRus/quorum-reborn/blob/master/resources/Quorum-128/Schematics/Q128P2M.PNG
2. https://github.com/UncleRus/quorum-reborn/blob/master/resources/Quorum-128/Schematics/ULA.png

Нужно понять, какая именно из них является действительной. Прошу владельцев Кворума-128 помочь в этом вопросе.

**Comment by atsidaev** [comment]
ULA.png, судя по подписи - это схема от Кворума-128+. Еще на ней светодиод питания (на Кворуме-128 его нет) и БП, выдающий не только 5 вольт, но и 12 (которые нужны 128+ для ВГ93 но не нужны простому 128). Правда, насколько помню, у БП 128+ напряжения должны быть выше, 9 и 17 нестабилизированных вольт, но возможно, что внутри компа стоит ещё одна доп. плата с кренками (ну типа как у БК-04).

**Comment by UncleRus** [comment]
Спасибо большое! Схему от 128+ перенес в отдельный каталог.
